seed: 1
device: cuda

data:
  root: data/mnist
  train_split: train
  val_split: val
  num_classes: 10
  img_size: 28

models:
  efficientnet_b3:
    output_dir: runs/efficientnet_b3
    transforms:
      train:
        ensure_rgb: true
        train_resize: true
        train_random_crop: true
        train_center_crop: false
        train_random_resized_crop: false
        train_random_horizontal_flip: false
        train_random_rotation: true
        train_color_jitter: false
        train_random_erasing: false
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    training:
      epochs: 10
      batch_size: 64
      num_workers: 8
      resume: auto
  efficientformer_v2_s1:
    output_dir: runs/efficientformer_v2_s1
    transforms:
      train:
        ensure_rgb: true
        train_resize: true
        train_random_crop: true
        train_center_crop: false
        train_random_resized_crop: false
        train_random_horizontal_flip: false
        train_random_rotation: true
        train_color_jitter: false
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    training:
      epochs: 12
      batch_size: 128
      num_workers: 8
      resume: auto
  faster_vit_2_224:
    output_dir: runs/faster_vit_2_224
    transforms:
      train:
        ensure_rgb: true
        train_resize: true
        train_random_crop: true
        train_center_crop: false
        train_random_resized_crop: false
        train_random_horizontal_flip: false
        train_random_rotation: true
        train_color_jitter: false
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    training:
      epochs: 12
      batch_size: 96
      num_workers: 8
      resume: auto

selection:
  - efficientnet_b3
  - efficientformer_v2_s1
  - faster_vit_2_224
