# FasterViT training configuration
batch_size: 32
epochs: 3
learning_rate: 0.001
weight_decay: 1e-5
image_size: 224
num_workers: 8
model_name: faster_vit_2_224
model_dir: fastervit_2_224_1k.pth
pretrained: true
dataset:
  train: Dataset/train
  val: Dataset/validation
  test: Dataset/test
