name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint (Ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install ruff
        run: pip install ruff
      - name: Lint (Ruff)
        run: ruff check .

  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install pytest only
        run: pip install pytest
      - name: Run smoke tests
        run: pytest -q -k "smoke" || pytest -q
